mapbox/mapbox-vision-android

MapboxVision/src/main/java/com/mapbox/vision/sensors/SensorsRequestsManager.kt
Set rotation rate to gyroscope instead of rotation sensor (which returns rotation not rate but rotation itself).
=> Fixed calibration non working

MapboxVision/src/main/java/com/mapbox/vision/corewrapper/update/jni/JNICoreUpdateManager.kt
Fix for
https://github.com/mapbox/mapbox-vision-android/issues/26
=> Remove thread handler. 

MapboxVision/src/main/java/com/mapbox/vision/telemetry/TelemetryManager.kt, MapboxVision/src/main/java/com/mapbox/vision/video/videoprocessor/VideoProcessor.kt
=> Save video clips with format `xx.yy_xx.yy.mp4`.

MapboxVision/src/main/java/com/mapbox/vision/VisionManager.kt, MapboxVision/src/main/java/com/mapbox/vision/telemetry/TelemetryManager.kt, gradle/versions.gradle
fixes mapbox/cv-assist#622
Example of user agent after the PR: `com.mapbox.vision.examples.debug/0.1.2/6 MapboxVision/0.1.2`
=> Use new telemetry SDK that fixes useragent issue.

MapboxVision/src/main/java/com/mapbox/vision/sensors/SensorsRequestsManager.kt
According the https://github.com/mapbox/cv-assist/pull/691
=> Update sensor manager, pass raw sensor without changes.

MapboxVision/src/main/java/com/mapbox/vision/telemetry/TelemetryManager.kt
=> Set full locale name instead of only country.

MapboxVision/src/main/java/com/mapbox/vision/telemetry/TelemetryManager.kt
=> Fix uninitialized uuid.

MapboxVision/src/main/java/com/mapbox/vision/telemetry/TelemetryManager.kt
=> Add timezone to telemetry session id.

MapboxVision/src/main/java/com/mapbox/vision/video/videosource/camera/CameraVideoSourceImpl.kt
https://github.com/mapbox/cv-assist/issues/627 fix
=> Add checking for init.

Examples/src/main/java/com/mapbox/vision/examples/ArActivity.java, Examples/src/main/java/com/mapbox/vision/examples/ExternalCameraSource.java, Examples/src/main/java/com/mapbox/vision/examples/SafetyActivity.java, Examples/src/main/kotlin/com/mapbox/vision/examples/ArActivityKt.kt, Examples/src/main/kotlin/com/mapbox/vision/examples/ExternalCameraSourceKt.kt, Examples/src/main/kotlin/com/mapbox/vision/examples/SafetyActivityKt.kt
(cherry picked from commit b790e6a)
=> Update Example activities.

build.gradle, settings.gradle
=> Fix settings gradle

Examples/src/main/AndroidManifest.xml
=> Foreground services: permission for API 28+

MapboxVision/src/main/java/com/mapbox/vision/VisionManager.kt, MapboxVision/src/main/java/com/mapbox/vision/telemetry/SessionManager.kt, MapboxVision/src/main/java/com/mapbox/vision/view/VisionView.kt
=> - crash fix;

Examples/src/main/java/com/mapbox/vision/examples/ArActivity.java
`directionsRoute` in `ArActivity` is never initialized, change to the right route object.
=> Fix wrong reroute param.

MapboxVision/src/main/java/com/mapbox/vision/VisionManager.kt
=> Fix country list

MapboxVision/build.gradle, gradle/versions.gradle
closes [1445](https://app.zenhub.com/workspaces/vision-sdk-5ca52e6c027e3e7234ac7512/issues/mapbox/mapbox-vision/1445)
=> Navigation lib update 0.40.0 -> 0.41.0

MapboxVision/build.gradle, build.gradle, gradle/jacoco.gradle
=> add jacoco

MapboxVision/src/test/java/com/mapbox/vision/dsl/VisionTestDsl.kt, MapboxVision/src/test/java/com/mapbox/vision/sync/telemetry/TotalBytesCounterTest.kt
=> add check for block display name

MapboxVision/src/test/java/com/mapbox/vision/sync/FeatureEnvironment.kt, MapboxVision/src/test/java/com/mapbox/vision/sync/FeatureEnvironmentTest.kt
=> add telemetry environment tests

MapboxVision/src/main/java/com/mapbox/vision/video/videosource/camera/Camera2VideoSourceImpl.kt
=> repeat create session on fail

MapboxVision/src/test/java/com/mapbox/vision/dsl/VisionTestDsl.kt
=> add verify block for test dsl

MapboxVision/src/main/java/com/mapbox/vision/sync/SessionManager.kt, MapboxVision/src/main/java/com/mapbox/vision/sync/syncmanager/TelemetrySyncManager.kt
closes [1520](https://app.zenhub.com/workspaces/vision-sdk-5ca52e6c027e3e7234ac7512/issues/mapbox/mapbox-vision/1520)
=> Delete telemetry fix

MapboxVision/gradle.properties, MapboxVisionAR/gradle.properties, MapboxVisionSafety/gradle.properties
=> update version to 0.9.0

Examples/build.gradle, Examples/src/main/java/com/mapbox/vision/examples/ArActivity.java, Examples/src/main/java/com/mapbox/vision/examples/BaseActivity.java, Examples/src/main/java/com/mapbox/vision/examples/ExternalCameraSource.java, Examples/src/main/java/com/mapbox/vision/examples/SafetyActivity.java, Examples/src/main/kotlin/com/mapbox/vision/examples/ArActivityKt.kt, Examples/src/main/kotlin/com/mapbox/vision/examples/ExternalCameraSourceKt.kt, Examples/src/main/kotlin/com/mapbox/vision/examples/SafetyActivityKt.kt, build.gradle, gradle/versions.gradle
Now Examples are compiled with released VisionSDK only.
closes [1684](https://app.zenhub.com/workspaces/vision-sdk-5ca52e6c027e3e7234ac7512/issues/mapbox/mapbox-vision/1684)
=> Knn examples fix

CHANGELOG.md
=> Release 0.10.1
